server:
  port: 8800
#  servlet:
#    context-path: /cloud-platform


logging:
  level:
    cn.cat.platform: debug


spring:
  datasource:
    name: cloud_platform
    url: jdbc:mysql://47.93.19.109:3306/cloud_platform_dev?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: wudonglong
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jackson:
    default-property-inclusion: non_null

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  # 注意：对应实体类的路径
  type-aliases-package: cn.cat.platform.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
